const { registerCommand } = require('../lib/commands/registry');

registerCommand('rate', async ({ sock, message, args }) => {
  const jid = message.key.remoteJid;

  const thing = args.length > 0 ? args.join(' ') : 'this';
  const rating = Math.floor(Math.random() * 101);

  let emoji;
  if (rating >= 90) emoji = '🔥🔥🔥';
  else if (rating >= 70) emoji = '😍😍';
  else if (rating >= 50) emoji = '😊';
  else if (rating >= 30) emoji = '😐';
  else if (rating >= 10) emoji = '😬';
  else emoji = '💀';

  const bar = '█'.repeat(Math.floor(rating / 10)) + '░'.repeat(10 - Math.floor(rating / 10));

  await sock.sendMessage(jid, {
    text: `📊 *Rate Command*\n\n` +
      `I rate *${thing}*...\n\n` +
      `${bar} *${rating}/100* ${emoji}\n\n` +
      `_Generated by MANU-BOT_`
  });
});
