const { registerCommand } = require('../lib/commands/registry');

registerCommand('ship', async ({ sock, message, args }) => {
  const jid = message.key.remoteJid;

  if (!jid.endsWith('@g.us')) {
    await sock.sendMessage(jid, { text: '❌ This command only works in groups.' });
    return;
  }

  try {
    const groupMetadata = await sock.groupMetadata(jid);
    const participants = groupMetadata.participants;

    if (participants.length < 2) {
      await sock.sendMessage(jid, { text: '❌ Need at least 2 members to ship!' });
      return;
    }

    // Pick two random different people
    let index1 = Math.floor(Math.random() * participants.length);
    let index2 = Math.floor(Math.random() * participants.length);
    while (index2 === index1) {
      index2 = Math.floor(Math.random() * participants.length);
    }

    const person1 = participants[index1];
    const person2 = participants[index2];
    const lovePercent = Math.floor(Math.random() * 101);

    let loveEmoji;
    if (lovePercent >= 90) loveEmoji = '💕💕💕';
    else if (lovePercent >= 70) loveEmoji = '❤️❤️';
    else if (lovePercent >= 50) loveEmoji = '💗';
    else if (lovePercent >= 30) loveEmoji = '💔';
    else loveEmoji = '☠️';

    const hearts = '❤️'.repeat(Math.ceil(lovePercent / 20));

    await sock.sendMessage(jid, {
      text: `💘 *Ship Command*\n\n` +
        `@${person1.id.split('@')[0]} 💕 @${person2.id.split('@')[0]}\n\n` +
        `Love Meter: ${hearts}\n` +
        `*${lovePercent}% Match!* ${loveEmoji}\n\n` +
        `_Generated by MANU-BOT_`,
      mentions: [person1.id, person2.id]
    });

  } catch (error) {
    console.error('❌ Ship error:', error.message);
    await sock.sendMessage(jid, { text: '❌ Failed to ship.' });
  }
});
