const { registerCommand } = require('../lib/commands/registry');
const fetch = require('node-fetch');

registerCommand('weather', async ({ sock, message, args }) => {
  const jid = message.key.remoteJid;

  if (!args.length) {
    await sock.sendMessage(jid, {
      text: '🌤️ *Weather*\n\nUsage: .weather <city>\n\nExample: .weather Nairobi'
    });
    return;
  }

  try {
    const city = args.join(' ');
    await sock.sendMessage(jid, { text: `🔍 Getting weather for *${city}*...` });

    const response = await fetch(`https://wttr.in/${encodeURIComponent(city)}?format=j1`);
    const data = await response.json();

    if (data.error) {
      await sock.sendMessage(jid, { text: `❌ City not found: ${city}` });
      return;
    }

    const current = data.current_condition[0];
    const area = data.nearest_area[0];

    const text =
      `🌤️ *Weather for ${area.areaName[0].value}, ${area.country[0].value}*\n\n` +
      `🌡️ *Temperature:* ${current.temp_C}°C / ${current.temp_F}°F\n` +
      `🤔 *Feels Like:* ${current.FeelsLikeC}°C\n` +
      `💧 *Humidity:* ${current.humidity}%\n` +
      `💨 *Wind:* ${current.windspeedKmph} km/h ${current.winddir16Point}\n` +
      `☁️ *Condition:* ${current.weatherDesc[0].value}\n` +
      `👁️ *Visibility:* ${current.visibility} km\n` +
      `🌡️ *Max/Min:* ${data.weather[0].maxtempC}°C / ${data.weather[0].mintempC}°C\n\n` +
      `_Generated by MANU-BOT_`;

    await sock.sendMessage(jid, { text });

    console.log(`✅ Weather sent for ${city}`);

  } catch (error) {
    console.error('❌ Weather error:', error.message);
    await sock.sendMessage(jid, { text: '❌ Failed to get weather. Please try again.' });
  }
});
